sale_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from sapo import views


router = routers.DefaultRouter()
router.register(r'products', views.ProductViewSet, basename='products')
router.register(r'customers', views.CustomerViewSet, basename='customers')
router.register(r'orders', views.OrderViewSet, basename='orders')
router.register(r'ordersitems', views.OrderItemViewSet, basename='ordersitems')
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('sapo.urls')),
    path('', RedirectView.as_view(url='')),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sapo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='index'),

]

###################--------------------------PRODUCTS----------------------###########################################################
urlpatterns += [
    path('products/', views.product_list, name='product_list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
]
urlpatterns += [
    path('add_product/', views.add_product, name='add_product'),
    path('update_product/<int:pk>/', views.update_product, name='update_product'),
    path('delete_product/<int:pk>/', views.delete_product, name='delete_product'),
]


###################--------------------------CUSTOMERS----------------------#######################################################

urlpatterns += [
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/<int:pk>/', views.customer_detail, name='customer_detail'),
    
]

urlpatterns += [
    path('update_customer/<int:pk>/', views.update_customer, name='update_customer'),
    path('delete_customer/<int:pk>/', views.delete_customer, name='delete_customer'),

]
urlpatterns += [
    path('add_customer/', views.add_customer, name='add_customer'),
]
######################--------------------------ORDERS----------------------#######################################################
urlpatterns += [
    path('orders/', views.order_list, name='order_list'),
    path('orders/<int:pk>/', views.order_detail, name='order_detail'),
]

urlpatterns += [
    path('update_order/<int:pk>/', views.update_order, name='update_order'),
    path('delete_order/<int:pk>/', views.delete_order, name='delete_order'),

]


urlpatterns += [
    path('add_order/', views.add_order, name='add_order'),
    path('update_orderitem/<int:pk>/', views.update_orderitem, name='update_orderitem'),
    path('delete_orderitem/<int:pk>/', views.delete_orderitem, name='delete_orderitem'),
    path('add_orderitem/', views.add_orderitem, name='add_orderitem'),
]


###################--------------------------login----------------------#######################################################

urlpatterns += [
    path('login/', views.auth_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
]








###############################################################################
urlpatterns += [
    path('direct_sale/', views.direct_sale, name='direct_sale'),
    path('update_item/', views.updateItem, name='update_item'),

]












##############################-----------export CSV------------------#######################
urlpatterns += [
    path('customer_csv/', views.customer_csv, name='customer_csv'),
    path('product_csv/', views.product_csv, name='product_csv'),
    path('order_csv/', views.order_csv, name='order_csv'),
    path('orderitem_csv/', views.orderitem_csv, name='orderitem_csv'),

]

################################-----------import CSV------------------#######################
urlpatterns += [
    path('customer_import/', views.import_csv_customer, name='customer_import'),
    path('product_import/', views.import_csv_product, name='product_import'),
    path('order_import/', views.import_csv_order, name='order_import'),
    path('orderitem_import/', views.import_csv_orderitem, name='orderitem_import'),
]


urlpatterns += [
    path('lobby/', views.lobby, name='lobby'),
]

sapo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=200, null=True, blank=True)
    category = models.CharField(max_length=255,null=True, blank=True)
    brand = models.CharField(max_length=255,null=True, blank=True)
    stock = models.IntegerField(null=True, blank=True)
    qr_code = models.CharField(max_length=255, null=True, blank=True)
    mass = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(upload_to='products', null=True, blank=True)
    tag = models.CharField(max_length=100, null=True, blank=True)
    import_price = models.DecimalField(default=0, max_digits=10, decimal_places=2, null=True, blank=True)
    wholesale_price = models.DecimalField(default=0,max_digits=10, decimal_places=2, null=True, blank=True)
    retail_price = models.DecimalField(default=0,max_digits=10, decimal_places=2, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    color = models.CharField(max_length=100, null=True, blank=True)
    unit_type =(
        ('kg', 'kilogram'),
        ('g', 'gam'),
    )
    unit = models.CharField(max_length=2, choices=unit_type, null=True, blank=True)

    status = models.BooleanField(default=True, null=True, blank=True)
    tax = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
class Customer(models.Model):
    
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=200, null=True, blank=True)
    sex = models.CharField(max_length=200, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    employee_care = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    debit = models.DecimalField(default=0, max_digits=10, decimal_places=2, null=True, blank=True)
    tag = models.CharField(max_length=100, null=True, blank=True)
    segment = models.CharField(max_length=100, null=True, blank=True)
    tax_code = models.CharField(max_length=100, null=True, blank=True)
    website = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    price_policy = models.CharField(max_length=100, null=True, blank=True)
    customer_discount = models.CharField(max_length=100, null=True, blank=True)
    payment = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return str(self.name)
    def get_absolute_url(self):
        return reverse('customer_detail', args=[str(self.id)])

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    code = models.CharField(max_length=200, null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    pay = models.BooleanField(default=False, null=True, blank=True)
    price_policy = models.CharField(max_length=100, null=True, blank=True)
    sale_location = models.CharField(max_length=100, null=True, blank=True)
    employee_sale = models.CharField(max_length=100, null=True, blank=True)
    ship_date = models.DateField(null=True, blank=True)
    source = models.CharField(max_length=100, null=True, blank=True)
    chanel = models.CharField(max_length=100, null=True, blank=True)
    path = models.CharField(max_length=100, null=True, blank=True)
    reference = models.CharField(max_length=100, null=True, blank=True)
    ship_address= models.CharField(max_length=100, null=True, blank=True)
    total = models.DecimalField(default=0, max_digits=10, decimal_places=2, null=True, blank=True)
    def __str__(self):
        return str(self.code)
    def get_absolute_url(self):
        return reverse('order_detail', args=[str(self.id)])

    
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total 

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total 

class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return str(self.order)
	@property
	def get_total(self):
		total = self.product.retail_price * self.quantity
		return total
     

class File(models.Model):
    file = models.FileField(upload_to='files')

sapo/forms.py
from django import forms
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from .models import *

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': field.label,
            })
            field.label = field.label.capitalize()   # add another name for label
            field.widget.attrs['style'] = 'margin-bottom: 10px;'
            field.help_text = mark_safe(field.help_text + '<br>') if field.help_text else ''

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': field.label,
            })
            field.label = field.label.capitalize()   # add another name for label
            field.widget.attrs['style'] = 'margin-bottom: 10px;'
            field.help_text = mark_safe(field.help_text + '<br>') if field.help_text else ''

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': field.label,
            })
            field.label = field.label.capitalize()
        self.fields['code'].label = "Mã đơn hàng"
        self.fields['customer'].label = "Khách hàng"
        self.fields['complete'].label = "Trạng thái đơn"
        self.fields['pay'].label = "Trạng thái thanh toán"
        self.fields['price_policy'].label = "Chính sách giá"
class OrderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': field.label,
            })

sapo/templates/sapo/IMPORT.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

 <form method="POST" enctype="multipart/form-data">
    {% csrf_token %} 
    <input type="file" name="file">
    <button type="submit">Lưu file</button>
</form>
{% endblock content%}

sapo/templates/sapo/customer_update.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3 class="text-center">Cập nhật Khách hàng</h3>
            <form method="POST" action="">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-success btn-block">Cập nhật</button>
            </form>
        </div>
    </div>
</div>

{% endblock content%}

sapo/templates/sapo/login.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">username</label>
      <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Password</label>
      <input type="password" name ="password" class="form-control" id="exampleInputPassword1">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock content%}

sapo/templates/sapo/order_create.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3 class="text-center">Thêm đơn hàng</h3>
            <form method="POST" action="">
                {% csrf_token %}
                {{ form }}
                <br>
                <button type="submit" class="btn btn-success btn-block">Thêm</button>
                &nbsp;<a href="{% url 'order_list' %}" class="btn btn-danger btn-block ">Hủy</a>
            </form>
        </div>
    </div>
</div>

{% endblock content%}

sapo/templates/sapo/order_detail.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<style>
    body {
        background-color: rgb(231, 231, 231);
    }
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="position: absolute; top: 0; left: 249px; right: 0; z-index: 1000;">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand nav-link btn btn-outline-secondary " href="{% url 'order_list' %}" style="margin-left: auto;font-family: 'Roboto', sans-serif;"><i class="bi bi-caret-left-fill me-2"></i><strong>Quay lại danh sách đơn hàng</strong></a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ms-auto">
        <a class="btn btn-outline-danger me-3" href="{% url 'delete_order' order.pk %}">Hủy đơn hàng</a>
        <a class="btn btn-outline-primary me-3" href="{% url 'update_order' order.pk %}">Sửa đơn hàng</a>
        <a class="btn btn-primary me-3" href="#">Đổi trả hàng</a>  
    </div>
  </div>
</nav>

<div class="container-fluid mt-5">
<h1>{{ order.code }}</h1>
<button class="btn btn-secondary btn-sm" onclick="copyToClipboard('{{ order.code }}')">Sao chép</button>
</div>
<script>
function copyToClipboard(text) {
    navigator.clipboard.writeText(text);
}
</script>
<div class="container-fluid mt-5" style="border: 1px solid white; border-radius: 5px; padding: 20px; background-color: white;width: 66%;float: left;">
    <h5>Thông tin đơn hàng</h5>
    <hr>
<div class="container-fluid mt-3">
    <div class="row mb-3">
        <div class="col-sm-6 mb-2" style="width: 50%;"> 
        <table class="table table-borderless">
        <tbody>
            <tr>
                <td style="width: 50%;"><label for="id_category" class="form-label">Chính sách giá</label></td>
                <td style="width: 50%;">:&nbsp;&nbsp;{{ order.price_policy }}</td>
            </tr>
            <tr>
                <td><label for="id_category" class="form-label">Bán tại</label></td>
                <td>:&nbsp;&nbsp;{{ order.sale_location }}</td>
            </tr>
            <tr>
                <td><label for="id_brand" class="form-label">Bán bởi</label></td>
                <td>:&nbsp;&nbsp;{{ order.employee_sale}}</td>
            </tr>
            <tr>
                <td><label for="id_brand" class="form-label">Hẹn giao hàng</label></td>
                <td>:&nbsp;&nbsp;{{ order.ship_date|date:"d/m/Y" }}</td>
            </tr>
            <tr>
                <td style="width: 50%;"><label for="id_category" class="form-label">Nguồn</label></td>
                <td style="width: 50%;">:&nbsp;&nbsp;{{ order.source }}</td>
            </tr>
        </tbody>
        </table>

        </div>

        <div class="col-sm-6 mb-2" style="width: 50%;">
            <table class="table table-borderless">
                <tbody>
                    <tr>
                        <td><label for="id_category" class="form-label">Kênh bán hàng</label></td>
                        <td>:&nbsp;&nbsp;{{ order.chanel }}</td>
                    </tr>
                    <tr>
                        <td><label for="id_brand" class="form-label">Ngày bán</label></td>
                        <td>:&nbsp;&nbsp;{{ order.date_created|date:"d/m/Y H:i" }}</td>
                    </tr>
                    <tr>
                        <td><label for="id_brand" class="form-label">Đường dẫn</label></td>
                        <td>:&nbsp;&nbsp;{{ order.path }}</td>
                    </tr>
                    <tr>
                        <td><label for="id_brand" class="form-label">Tham chiếu</label></td>
                        <td>:&nbsp;&nbsp;{{ order.reference }}</td>
                    </tr>
                </tbody>
                </table>

        </div>
        <div class="col-sm-6 mb-2"style="width: 35%;">
            <img src="{{ product.image.url }}" alt="{{ product.image }}" class="img-fluid rounded" >
        </div>
    </div>
</div>
</div>
<div class="container-fluid mt-5" style="border: 1px solid white; border-radius: 5px; padding: 20px; background-color: white;width: 33%; float: right;">
    <h5>Thông tin khách hàng</h5>
    <hr>
    <div class="container-fluid mt-3">
        <div class="row mb-3">
            <div class="col-sm-6 mb-2" style="width: 100%;"> 
            <table class="table table-borderless">
            <tbody>
                <tr>
                    <td style="width: 50%;"><label for="id_code" class="form-label">Tên khách hàng</label></td>
                    <td style="width: 50%;">:&nbsp;&nbsp;{{ order.customer }}</td>
                </tr>
                <tr>
                    <td><label for="id_qr_code" class="form-label">Địa chỉ giao hàng</label></td>
                    <td>:&nbsp;&nbsp;{{ order.ship_address }}</td>
                </tr>
                <tr>
                    <td><label for="id_qr_code" class="form-label">Số điện thoại</label></td>
                    <td>:&nbsp;&nbsp;{{ order.customer.phone }}</td>
                </tr>
                <tr>
                    <td><label for="id_qr_code" class="form-label">Địa chỉ</label></td>
                    <td>:&nbsp;&nbsp;{{ order.customer.address }}</td>
                </tr>


            </tbody>
            </table>
    
            </div>
    
            <div class="col-sm-6 mb-2"style="width: 40%;">
                <img src="{{ product.image.url }}" alt="{{ product.image }}" class="img-fluid rounded" >
            </div>
        </div>
    </div>
</div>
<div class="container-fluid mt-5" style="border: 1px solid white; border-radius: 5px; padding: 20px; background-color: white; height: 280px; float: left;">
    <h5>CÒN CÁI LIÊN KẾT VS BẢNG KHÁC MÀ ĐỂ SAU</h5>
    <hr>
    <div class="container-fluid mt-3">
        <div class="row mb-3">
            <div class="col-sm-6 mb-2" style="width: 60%;"> 
            <table class="table table-borderless">
            <tbody>
                <tr>
                    <td><label for="id_qr_code" class="form-label">Giá bán lẻ</label></td>
                    <td>:&nbsp;&nbsp;{{ product.retail_price }}</td>
                </tr>
                <tr>
                    <td style="width: 50%;"><label for="id_code" class="form-label">Giá bán buôn</label></td>
                    <td style="width: 50%;">:&nbsp;&nbsp;{{ product.wholesale_price }}</td>
                </tr>
                <tr>
                    <td><label for="id_qr_code" class="form-label">Giá nhập</label></td>
                    <td>:&nbsp;&nbsp;{{ product.import_price }}</td>
                </tr>

            </tbody>
            </table>
    
            </div>
        </div>
    </div>
    
</div>
<div class="container-fluid mt-5" style="border: 1px solid white; border-radius: 5px; padding: 20px; background-color: white; float: left;">
    <h5>Lịch sử mua hàng</h5>
    <hr>
    <div class="container-fluid mt-3">
        <div class="row mb-3">
       
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Mã đơn hàng</th>
                            <th>Tên sản phẩm</th>
                            <th>Số luong</th>
                            <th>Ngày thêm</th>
                            <th>Chỉnh sửa</th>
                            
                        </tr>
                    </thead>
                    <tbody>

                        {% for orderitem in orderitems %}
                        <tr>
                            <td>{{ orderitem.order.code }}</td>
                            <td>{{ orderitem.product.name }}</td>
                            <td>{{ orderitem.quantity }}</td>
                            <td>{{ orderitem.date_added }}</td>
                            <td>
                                <a href="{% url 'update_orderitem' orderitem.id  %}" class="btn btn-success btn-sm">Cập nhật</a>
                                <a href="{% url 'delete_orderitem' orderitem.id  %}" class="btn btn-danger btn-sm">Xóa</a>
                            </td>
                        </tr>
                        {% endfor %}
                        
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="6" style="text-align: center;">
                                    <div style="display: flex; justify-content: center; width: 100%;">
                                        <a href="{% url 'add_orderitem'%}" class="btn btn-primary" style="flex-grow: 1;">Thêm sản phẩm</a>
                                    </div>
                                </td>
                            </tr>
                        </tfoot>
                    </tbody>
                </table>
          
        </div>
    </div>
    
</div>

{% endblock content %}

sapo/templates/sapo/order_update.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3 class="text-center">Cập nhật đơn hàng</h3>
            <form method="POST" action="">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-success btn-block">Cập nhật</button>
            </form>
        </div>
    </div>
</div>

{% endblock content%}

sapo/templates/sapo/orderitem_delete.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<style>
    body {
        background-color: rgb(231, 231, 231);
    }
</style>
<!-- <div class="container">
    <div class="col-auto">
        <div class="col-md-6 offset-md-3"> -->
            <form method="POST" action="">
                {% csrf_token %}
                <div class="col">
                    <h1 style="text-align: center;">Bạn muốn xóa sản phẩm này của đơn hàng: {{ order.code }}?</h1>
                    <hr>
                    <div class="row">
                        <button type="submit" class="btn btn-danger btn-block btn-lg">Xóa</button>
                    </div>
                    <br>
                    <div class="row">
                        <a href="{% url 'order_detail' orderitem.order.pk %}" class="btn btn-secondary btn-block btn-lg">Hủy</a>
                    </div>
                </div>
            </form>
        <!-- </div>
    </div>
</div> -->

{% endblock content%}

sapo/templates/sapo/orderitem_update.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3 class="text-center">Cập nhật Sản phẩm của đơn hàng</h3>
            <form method="POST" action="">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-success btn-block">Cập nhật</button>
            </form>
        </div>
    </div>
</div>

{% endblock content%}

sapo/templates/sapo/product_delete.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<!-- <div class="container">
    <div class="col-auto">
        <div class="col-md-6 offset-md-3"> -->
            <form method="POST" action="">
                {% csrf_token %}
                <div class="col">
                    <h1 style="text-align: center;">Bạn muốn xóa sản phẩm: {{ product.name }}?</h1>
                    <hr>
                    <div class="row">
                        <button type="submit" class="btn btn-danger btn-block btn-lg">Xóa</button>
                    </div>
                    <br>
                    <div class="row">
                        <a href="{% url 'product_list' %}" class="btn btn-secondary btn-block btn-lg">Hủy</a>
                    </div>
                </div>
            </form>
        <!-- </div>
    </div>
</div> -->

    <div class="container-fluid mt-5" style="border: 1px solid white; border-radius: 5px; padding: 20px; background-color: white;float: left;">
        <h5>Thông tin sản phẩm</h5>
        <hr>
    <div class="container-fluid mt-3">
        <div class="row mb-3">
            <div class="col-sm-6 mb-2" style="width: 32%;"> 
            <table class="table table-borderless">
            <tbody>
                <tr>
                    <td style="width: 50%;"><label for="id_code" class="form-label">Mã SKU:</label></td>
                    <td style="width: 50%;">{{ product.code }}</td>
                </tr>
                <tr>
                    <td><label for="id_qr_code" class="form-label">Mã Barcode:</label></td>
                    <td>{{ product.qr_code }}</td>
                </tr>
                <tr>
                    <td><label for="id_mass" class="form-label">Khối lượng:</label></td>
                    <td>{{ product.mass }}</td>
                </tr>
                <tr>
                    <td><label for="id_unit" class="form-label">Đơn vị tính:</label></td>
                    <td>{{ product.unit }}</td>
                </tr>
                <tr>
                    <td><label for="id_category" class="form-label">Phân loại:</label></td>
                    <td>{{ product.category }}</td>
                </tr>
            </tbody>
            </table>
            <a href="#" onclick="$('#description').toggle(); return false;">Xem mô tả</a>
            <table id="description" style="display: none;">
            <tbody>
                <tr>
                    <td colspan="2">{{ product.description|linebreaks }}</td>
                </tr>
            </tbody>
            </table>
    
            </div>
    
            <div class="col-sm-6 mb-2" style="width: 32%;">
                <table class="table table-borderless">
                    <tbody>
                        <tr>
                            <td style="width: 50%;"><label for="id_category" class="form-label">Loại sản phẩm:</label></td>
                            <td style="width: 50%;">{{ product.category }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_brand" class="form-label">Nhãn hiệu:</label></td>
                            <td>{{ product.brand }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_tag" class="form-label">Tags:</label></td>
                            <td>{{ product.tag }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_date_create" class="form-label">Ngày tạo:</label></td>
                            <td>{{ product.date_create|date:"d/m/Y" }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_date_update" class="form-label">Ngày cập nhật cuối :</label></td>
                            <td>{{ product.updated_at|date:"d/m/Y" }}</td>
                        </tr>
                    </tbody>
                    </table>
    
            </div>
            <div class="col-sm-6 mb-2"style="width: 35%;">
                <img src="{{ product.image.url }}" alt="{{ product.image }}" class="img-fluid rounded" >
            </div>
        </div>
    </div>

{% endblock content%}